export const english_productsInfo = [
    { id:66  , name: "Seeds" },
    { id:3  , name: "Apples" },
    { id:4  , name: "Oranges" },
    { id:5  , name: "Grapes" },
    { id:6  , name: "Grain" },
    { id:72  , name: "Sugarcane" },
    { id:40  , name: "Cotton" },
    { id:106  , name: "Wood" },
    { id:101  , name: "Reinforced concrete" },
    { id:102  , name: "Bricks" },
    { id:103  , name: "Cement" },
    { id:44  , name: "Sand" },
    { id:104  , name: "Clay" },
    { id:105  , name: "Limestone" },
    { id:107  , name: "Steel beams" },
    { id:108  , name: "Planks" },
    { id:109  , name: "Windows" },
    { id:110  , name: "Tools" },
    { id:111  , name: " Construction units " },
    { id:41  , name: "Fabric" },
    { id:60  , name: "Underwear" },
    { id:61  , name: "Gloves" },
    { id:62  , name: "Dress" },
    { id:63  , name: "Stiletto Heel" },
    { id:64  , name: "Handbags" },
    { id:65  , name: "Sneakers" },
    { id:70  , name: "Luxury watch" },
    { id:71  , name: "Necklace"        },
    { id:14  , name: "Minerals" },
    { id:15  , name: "Bauxite" },
    { id:68  , name: "Gold ore" },
    { id:42  , name: "Iron ore" },
    { id:16  , name: "Silicon" },
    { id:17  , name: "Chemicals" },
    { id:18  , name: "Aluminium" },
    { id:69  , name: "Golden bars" },
    { id:43  , name: "Steel" },
    { id:45  , name: "Glass" },
    { id:76  , name: "Carbon composite" },
    { id:67  , name: "Xmas crackers" },
    { id:80  , name: "Flight computer" },
    { id:81  , name: "Cockpit" },
    { id:82  , name: "Attitude control" },
    { id:98  , name: "Quadcopter" },
    { id:99  , name: "Satellite" },
    { id:48  , name: "Electric motor" },
    { id:52  , name: "Combustion engine" },
    { id:85  , name: "Solid fuel booster" },
    { id:86  , name: "Rocket engine" },
    { id:88  , name: "Ion drive" },
    { id:89  , name: "Jet engine" },
    { id:49  , name: "Luxury car interior" },
    { id:50  , name: "Basic interior" },
    { id:51  , name: "Car body" },
    { id:53  , name: "Economy e-car" },
    { id:54  , name: "Luxury e-car" },
    { id:55  , name: "Economy car" },
    { id:56  , name: "Luxury car" },
    { id:57  , name: "Truck" },
    { id:112  , name: "Bulldozer" },
    { id:77  , name: "Fuselage" },
    { id:78  , name: "Wing" },
    { id:84  , name: "Propellant tank" },
    { id:87  , name: "Heat shield" },
    { id:90  , name: "Sub-orbital 2nd stage" },
    { id:92  , name: "Orbital booster" },
    { id:93  , name: "Starship" },
    { id:10  , name: "Crude oil" },
    { id:74  , name: "Methane" },
    { id:11  , name: "Petrol" },
    { id:12  , name: "Diesel" },
    { id:19  , name: "Plastic" },
    { id:75  , name: "Carbon fibers" },
    { id:83  , name: "Rocket fuel" },
    { id:95  , name: "Jumbo jet" },
    { id:96  , name: "Luxury jet" },
    { id:97  , name: "Single engine plane" },
    { id:91  , name: "Sub-orbital rocket" },
    { id:94  , name: "BFR"    },
    { id:1  , name: "Electricity" },
    { id:2  , name: "Water" },
    { id:7  , name: "Steak" },
    { id:8  , name: "Sausages" },
    { id:9  , name: "Eggs" },
    { id:13  , name: "Transport" },
    { id:20  , name: "Processors" },
    { id:21  , name: "Electronic components" },
    { id:22  , name: "Batteries" },
    { id:23  , name: "Screens" },
    { id:24  , name: "Smartphones" },
    { id:25  , name: "Tablets" },
    { id:26  , name: "Laptops" },
    { id:27  , name: "Monitors" },
    { id:28  , name: "Televisions" },
    { id:29  , name: "Agricultural research" },
    { id:30  , name: "Energy research" },
    { id:31  , name: "Mining research" },
    { id:32  , name: "Electronic research" },
    { id:33  , name: "Livestock research" },
    { id:34  , name: "Chemical research" },
    { id:35  , name: "Software" },
    { id:46  , name: "Leather" },
    { id:47  , name: "On-board computer" },
    { id:58  , name: "Automotive Research" },
    { id:59  , name: "Fashion research" },
    { id:73  , name: "Ethanol" },
    { id:79  , name: "High grade electronics" },
    { id:100  , name: "Aerospace research" },
    { id:113  , name: "Investigation of materials" },
    { id:114  , name: "Robots" },
]