export const spanish_productsInfo = [
    {id: 66, name: "Semillas"},
    {id: 3, name: "Manzanas"},
    {id: 4, name: "Naranjas"},
    {id: 5, name: "Uvas"},
    {id: 6, name: "Grano"},
    {id: 72, name: "Caña de azúcar"},
    {id: 40, name: "Algodón"},
    {id: 106, name: "Madera"},
    {id: 101, name: "Hormigón armado"},
    {id: 102, name: "Bloques"},
    {id: 103, name: "Cemento"},
    {id: 44, name: "Arena"},
    {id: 104, name: "Arcilla"},
    {id: 105, name: "Caliza"},
    {id: 107, name: "Vigas de acero"},
    {id: 108, name: "Tablones"},
    {id: 109, name: "Ventanas"},
    {id: 110, name: "Herramientas"},
    {id: 111, name: "Unidades de construcción"},
    {id: 41, name: "Tela"},
    {id: 60, name: "Ropa interior"},
    {id: 61, name: "Guantes"},
    {id: 62, name: "Vestido"},
    {id: 63, name: "Tacón"},
    {id: 64, name: "Bolsos"},
    {id: 65, name: "Zapatillas"},
    {id: 70, name: "Reloj de lujo"},
    {id: 71, name: "Collar"},
    {id: 14, name: "Minerales"},
    {id: 15, name: "Bauxita"},
    {id: 68, name: "Mineral de oro"},
    {id: 42, name: "Mineral de hierro"},
    {id: 16, name: "Silicon"},
    {id: 17, name: "Químicos"},
    {id: 18, name: "Aluminio"},
    {id: 69, name: "Barras de oro"},
    {id: 43, name: "Acero"},
    {id: 45, name: "Vidrio"},
    {id: 76, name: "Compuesto de carbono"},
    {id: 67, name: "Sorpresas navideñas"},
    {id: 80, name: "Computadora de vuelo"},
    {id: 81, name: "Cabina"},
    {id: 82, name: "Control de actitud"},
    {id: 98, name: "Cuadricóptero"},
    {id: 99, name: "Satélite"},
    {id: 48, name: "Motor eléctrico"},
    {id: 52, name: "Motor de combustión"},
    {id: 85, name: "Propulsor sólido"},
    {id: 86, name: "Motor cohete"},
    {id: 88, name: "Propulsor iónico"},
    {id: 89, name: "Motor de turbina"},
    {id: 49, name: "Interior de coche de lujo"},
    {id: 50, name: "Interior básico"},
    {id: 51, name: "Carrocería"},
    {id: 53, name: "E-car económico"},
    {id: 54, name: "E-car de lujo"},
    {id: 55, name: "Coche económico"},
    {id: 56, name: "Coche de lujo"},
    {id: 57, name: "Camión"},
    {id: 112, name: "Excavadora"},
    {id: 77, name: "Fuselaje"},
    {id: 78, name: "Ala"},
    {id: 84, name: "Tanque de propelente"},
    {id: 87, name: "Escudo térmico"},
    {id: 90, name: "Segunda etapa suborbital"},
    {id: 92, name: "Amplificador orbital"},
    {id: 93, name: "Starship"},
    {id: 10, name: "Petróleo"},
    {id: 74, name: "Metano"},
    {id: 11, name: "Gasolina"},
    {id: 12, name: "Diesel"},
    {id: 19, name: "Plástico"},
    {id: 75, name: "Fibras de carbono"},
    {id: 83, name: "Combustible de cohete"},
    {id: 95, name: "Jumbo jet"},
    {id: 96, name: "Jet de lujo"},
    {id: 97, name: "Avioneta"},
    {id: 91, name: "Cohete suborbital"},
    {id: 94, name: "BFR"},
    {id: 1, name: "Electricidad"},
    {id: 2, name: "Agua"},
    {id: 7, name: "Bistec"},
    {id: 8, name: "Salchichas"},
    {id: 9, name: "Huevos"},
    {id: 13, name: "Transporte"},
    {id: 20, name: "Procesadores"},
    {id: 21, name: "Componentes electrónicos"},
    {id: 22, name: "Baterías"},
    {id: 23, name: "Pantallas"},
    {id: 24, name: "Smartphones"},
    {id: 25, name: "Tablets"},
    {id: 26, name: "Laptops"},
    {id: 27, name: "Monitores"},
    {id: 28, name: "Televisores"},
    {id: 29, name: "Investigación agrícola"},
    {id: 30, name: "Investigación energética"},
    {id: 31, name: "Investigación minera"},
    {id: 32, name: "Investigación electrónica"},
    {id: 33, name: "Investigación ganadera"},
    {id: 34, name: "Investigación química"},
    {id: 35, name: "Software"},
    {id: 46, name: "Cuero"},
    {id: 47, name: "Computadora de a bordo"},
    {id: 58, name: "Investigación automotriz"},
    {id: 59, name: "Investigación de moda"},
    {id: 73, name: "Etanol"},
    {id: 79, name: "Electrónicos de alto grado"},
    {id: 100, name: "Investigación aeroespacial"},
    {id: 113, name: "Investigación de materiales"},
    {id: 114, name: "Robots"},
]